using DentFlow.Patients.Domain;
namespace DentFlow.Patients.Application;
public record PatientResponse(
    Guid Id,
    string PatientNumber,
    string FirstName,
    string LastName,
    string? PreferredName,
    string? ParentName,
    string FullName,
    string DisplayName,
    DateOnly? DateOfBirth,
    Gender? Gender,
    string? Email,
    string? PhoneMobile,
    string? PhoneHome,
    string? PhoneWork,
    ContactMethod? PreferredContactMethod,
    string? AddressLine1,
    string? AddressLine2,
    string? City,
    string? StateProvince,
    string? PostalCode,
    string? CountryCode,
    PatientStatus Status,
    DateOnly? FirstVisitDate,
    DateOnly? LastVisitDate,
    DateOnly? RecallDueDate,
    Guid? PreferredProviderId,
    bool SmsOptIn,
    bool EmailOptIn,
    string? Notes,
    DateTime CreatedAt,
    DateTime? UpdatedAt)
{
    public static PatientResponse FromEntity(Patient p) => new(
        p.Id,
        p.PatientNumber,
        p.FirstName,
        p.LastName,
        p.PreferredName,
        p.ParentName,
        p.FullName,
        p.DisplayName,
        p.DateOfBirth,
        p.Gender,
        p.Email,
        p.PhoneMobile,
        p.PhoneHome,
        p.PhoneWork,
        p.PreferredContactMethod,
        p.AddressLine1,
        p.AddressLine2,
        p.City,
        p.StateProvince,
        p.PostalCode,
        p.CountryCode,
        p.Status,
        p.FirstVisitDate,
        p.LastVisitDate,
        p.RecallDueDate,
        p.PreferredProviderId,
        p.SmsOptIn,
        p.EmailOptIn,
        p.Notes,
        p.CreatedAt,
        p.UpdatedAt);
}
